/**
 * Alert feed.
 *
 * Alerts are generated by the irrigation and crop-health engines rather than
 * created directly by users. This module owns reading and acknowledging them.
 */

import type { Prisma } from '@prisma/client';
import { prisma } from '../../common/prisma';
import { logger } from '../../common/logger';
import { NotFoundError } from '../../common/errors';

const SEVERITY_WEIGHT: Record<string, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
  INFO: 4,
};

export interface ListAlertsOptions {
  unreadOnly: boolean;
  severity?: string;
  limit: number;
}

export async function listAlerts(farmId: string, userId: string, options: ListAlertsOptions) {
  await assertFarmOwned(farmId, userId);

  const where: Prisma.AlertWhereInput = {
    farmId,
    isDismissed: false,
    OR: [{ expiresAt: null }, { expiresAt: { gte: new Date() } }],
  };
  if (options.unreadOnly) where.isRead = false;
  if (options.severity) where.severity = options.severity as Prisma.AlertWhereInput['severity'];

  const alerts = await prisma.alert.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    take: options.limit,
    include: { crop: { select: { id: true, cropName: true } } },
  });

  // Sort by severity first, recency second. Prisma cannot order by enum
  // priority directly, so it is done here on an already-bounded result set.
  alerts.sort((a, b) => {
    const bySeverity = (SEVERITY_WEIGHT[a.severity] ?? 9) - (SEVERITY_WEIGHT[b.severity] ?? 9);
    return bySeverity !== 0 ? bySeverity : b.createdAt.getTime() - a.createdAt.getTime();
  });

  const shaped = alerts.map((alert) => {
    const meta = alert.metadata as { title?: string; action?: string; source?: string } | null;
    return {
      id: alert.id,
      alertType: alert.alertType,
      severity: alert.severity,
      title: meta?.title ?? defaultTitle(alert.alertType),
      message: alert.message,
      action: meta?.action ?? null,
      source: meta?.source ?? null,
      crop: alert.crop,
      isRead: alert.isRead,
      createdAt: alert.createdAt,
      expiresAt: alert.expiresAt,
    };
  });

  return {
    alerts: shaped,
    counts: {
      total: shaped.length,
      unread: shaped.filter((a) => !a.isRead).length,
      critical: shaped.filter((a) => a.severity === 'CRITICAL').length,
      high: shaped.filter((a) => a.severity === 'HIGH').length,
    },
  };
}

export async function markRead(alertId: string, userId: string): Promise<void> {
  const alert = await prisma.alert.findFirst({
    where: { id: alertId, farm: { userId } },
    select: { id: true },
  });
  if (!alert) throw new NotFoundError('Alert', alertId);
  await prisma.alert.update({ where: { id: alertId }, data: { isRead: true } });
}

export async function dismiss(alertId: string, userId: string): Promise<void> {
  const alert = await prisma.alert.findFirst({
    where: { id: alertId, farm: { userId } },
    select: { id: true },
  });
  if (!alert) throw new NotFoundError('Alert', alertId);
  await prisma.alert.update({
    where: { id: alertId },
    data: { isDismissed: true, isRead: true },
  });
  logger.debug({ alertId }, 'Alert dismissed');
}

export async function markAllRead(farmId: string, userId: string): Promise<number> {
  await assertFarmOwned(farmId, userId);
  const result = await prisma.alert.updateMany({
    where: { farmId, isRead: false, isDismissed: false },
    data: { isRead: true },
  });
  return result.count;
}

async function assertFarmOwned(farmId: string, userId: string): Promise<void> {
  const farm = await prisma.farm.findFirst({
    where: { id: farmId, userId },
    select: { id: true },
  });
  if (!farm) throw new NotFoundError('Farm', farmId);
}

function defaultTitle(alertType: string): string {
  const titles: Record<string, string> = {
    WEATHER_RISK: 'Weather risk',
    IRRIGATION_NEEDED: 'Irrigation due',
    DISEASE_DETECTED: 'Possible disease',
    PEST_DETECTED: 'Possible pest',
    NUTRIENT_DEFICIENCY: 'Nutrient deficiency',
    HARVEST_WINDOW: 'Harvest window',
    PRICE_OPPORTUNITY: 'Price opportunity',
    FROST_WARNING: 'Frost warning',
    HEAT_STRESS: 'Heat stress',
    FLOOD_RISK: 'Heavy rain / flood risk',
    DROUGHT_RISK: 'Dry spell',
  };
  return titles[alertType] ?? 'Alert';
}
